### ISSUE TITLE
Pretrained Model Weights

### ISSUE THREAD

**Issue by LzqInsta** [jimmy19991222/ELFNet#1]
Hello! Thanks for your great work and kindly opening source code.
Would you release your pretrained model in near future, which can reproduce the results in the paper

**Comment by jimmy19991222** [comment]
Hi, thank you for your interest in the project. We will upload the pretrained model soon.

**Comment by LzqInsta** [comment]
thanks for your quick reply. Since I have encountered a problem of ”CUDA out of memory“ on a 3090 gpu for training，a pretrained model is necessary for me.

**Comment by jimmy19991222** [comment]
Hi, I have released the pretrained weight. You can download from this google drive link (https://drive.google.com/file/d/16ViZY16-rtTK1oFnMAmlahh3gXfEAVCP/view?usp=share_link). 

torch.cuda.checkpoint (in sttr) and torch.cuda.amp are applied to optimize memory usage during training to avoid OOM problem. If you still cannot train the model, you can apply torch.cuda.checkpoint on cost-volume-based model as well. You can try to adjust the size of random crop to save memory but may affect results. https://github.com/jimmy19991222/ELFNet/blob/9b0cb450fc8c526906f0356a121337aa36a42e4b/dataset/stereo_albumentation.py#L114

**Comment by LzqInsta** [comment]
thanks for your advice and released model weights!
